title: Team Tokyo Metis
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://github.com/MetisMontessoriLyceum/team-tokyo-metis
baseurl: "/team-tokyo-metis"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

prose:
  siteurl: "https://metismontessorilyceum.github.io/team-tokyo-metis/"
  media: /assets/img
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: image
        field:
          element: text
          placeholder: 'Featured image'
          help: 'upload image to /assets/img'
    layout: post

# google_analytics: "UA-58263416-1"
