title: Team Tokyo Metis
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://github.com/MetisMontessoriLyceum/team-tokyo-metis
baseurl: "/team-tokyo-metis"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about/
 - title: Contact
   url: /contact/

social:
   github: MetisMontessoriLyceum
   twitter: metisrobotica
   email: m.scale@coderclass.nl

prose:
  siteurl: "https://metismontessorilyceum.github.io/team-tokyo-metis/"
  media: /assets/img
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: image
        field:
          element: text
          label: 'Featured image'
          placeholder: 'image.png'
          help: 'upload image to /assets/img'
    layout: post

google_analytics: UA-83684754-3
